// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("exchange2crm.WebJob")]
[assembly: AssemblyProductAttribute("exchange2crm")]
[assembly: AssemblyDescriptionAttribute("Import Office 365 Exchange Contact to Microsoft Dynamics CRM")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
